### ISSUE TITLE
make clean

### ISSUE THREAD

**Issue by igagis** [igagis/prorab#18]
when cleaning project utki, src/obj is not removed and ldflags.txt remains in it

**Comment by igagis** [comment]
most likely it is not a bug in prorab, but in utki, as it redefines the default object directory and does not revert it.

**Comment by mzemb** [comment]
I suggest using the clean command of your source control software instead of the one of the build system.

**Comment by igagis** [comment]
@mzemb thanks for suggestion, but the bug in the build system should also be fixed, and I have just done it.
